// <auto-generated />
using System;
using Lesson06_EFCore_CodeFIrst.Models.BusinessModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lesson06_EFCore_CodeFIrst.Migrations
{
    [DbContext(typeof(BusinessDBContext))]
    [Migration("20260924134403_SeedDataInitial")]
    partial class SeedDataInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lesson06_EFCore_CodeFIrst.Models.DataModels.Book", b =>
                {
                    b.Property<string>("BookId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int?>("Release")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = "P68050",
                            Author = "Keith Ferrazzi",
                            CategoryId = 1,
                            Description = "Sách kỹ năng giao tiếp",
                            Picture = "images/books/P68050.jpg",
                            Price = 95000.0,
                            PublisherId = 1,
                            Release = 2016,
                            Title = "Đừng Bao Giờ Đi Ăn Một Mình"
                        },
                        new
                        {
                            BookId = "P67842",
                            Author = "Yoshito Usui",
                            CategoryId = 3,
                            Description = "Truyện tranh",
                            Picture = "images/books/P67842.jpg",
                            Price = 18000.0,
                            PublisherId = 2,
                            Release = 2016,
                            Title = "Shin - Cậu Bé Bút Chì"
                        });
                });

            modelBuilder.Entity("Lesson06_EFCore_CodeFIrst.Models.DataModels.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Sách kinh tế"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Sách tin học"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sách thiếu nhi"
                        });
                });

            modelBuilder.Entity("Lesson06_EFCore_CodeFIrst.Models.DataModels.Publisher", b =>
                {
                    b.Property<int>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PublisherId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PublisherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PublisherId");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            PublisherId = 1,
                            Address = "Hà Nội",
                            Phone = "098746533",
                            PublisherName = "Nhà xuất bản trẻ"
                        },
                        new
                        {
                            PublisherId = 2,
                            Address = "Hà Nội",
                            Phone = "096833435",
                            PublisherName = "Nhà xuất bản Kim Đồng"
                        });
                });

            modelBuilder.Entity("Lesson06_EFCore_CodeFIrst.Models.DataModels.Book", b =>
                {
                    b.HasOne("Lesson06_EFCore_CodeFIrst.Models.DataModels.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Lesson06_EFCore_CodeFIrst.Models.DataModels.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId");

                    b.Navigation("Category");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Lesson06_EFCore_CodeFIrst.Models.DataModels.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Lesson06_EFCore_CodeFIrst.Models.DataModels.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
